// <auto-generated />
using System;
using ConsoleApp2.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(GoodsContext))]
    [Migration("20230309070649_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("ConsoleApp2.DB.Category", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategory");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            IdCategory = new Guid("9aa9ae5e-615b-4cc8-8a7c-49947fc20718"),
                            Name = "Овощи"
                        },
                        new
                        {
                            IdCategory = new Guid("5cf656b3-d186-4062-b798-c5824d9a7002"),
                            Name = "Фрукты"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.DB.Good", b =>
                {
                    b.Property<Guid>("IdGood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryIdCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Sale")
                        .HasColumnType("REAL");

                    b.HasKey("IdGood");

                    b.HasIndex("CategoryIdCategory");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("ConsoleApp2.DB.Good", b =>
                {
                    b.HasOne("ConsoleApp2.DB.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryIdCategory");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
